### ISSUE TITLE
Nulls everywhere in BCEL view

### ISSUE THREAD

**Issue by mchorse** [ptnkjke/Java-Bytecode-Editor#3]
Hello there!

I was having few issues with the BCEL generated code. Most of the lines were covered with `null`s. I figured out that the problem was in the `private void visitCPInstruction(InstructionHandle instructionHandle)` method. I changed `NameSignatureInstruction` to `FieldOrMethod` (looks like some previous class was depreciated/renamed). After that, the code was generated without `null`s.

Anyways, thanks so much for making this! 😄 

P.S.: I think it would be very useful if you would add an instruction (in `README.md`) on how to setup this repository in an IDE (I used eclipse) 🙂

**Comment by ptnkjke** [comment]
Hello.

The project requires some support. 

My last commit changed bcel version. It (new version) has new several instructions, which should add to this project for supporting.

**Comment by ptnkjke** [comment]
I fixed 'null' in BCEL code.

**Comment by mchorse** [comment]
Thanks! 🙂 👍
