### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by joseboretto** [ptnkjke/Java-Bytecode-Editor#4]
Hi, I like your project.

I opened it with intelli j but the Main class does not compile.
Can you add a build folder where anyone can get the .JAR to run the program?

Thanks

**Comment by ptnkjke** [comment]
Hello
![capture3](https://user-images.githubusercontent.com/2806396/31048380-926ef050-a624-11e7-937c-4cfa63bba9e7.PNG)

I dont have any problem with start via intellij.

You need install maven for using this project.
